name: Python Tests & Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pylint mypy pytest pytest-cov black isort bandit
    - name: Check import sorting with isort
      run: |
        isort . --check-only --diff
    - name: Check code formatting with Black
      run: |
        black . --check --diff
    - name: Lint with flake8
      run: |
        flake8 . --count --max-line-length=120 --statistics --show-source --extend-ignore=E203
    - name: Lint with pylint
      run: |
        pylint src/ --rcfile=.pylintrc || true
    - name: Type checking with mypy
      run: |
        mypy src/ --ignore-missing-imports
    - name: Security check with bandit
      run: |
        bandit -r src/ -ll
    - name: Run tests with coverage
      run: |
        pytest --cov=src/ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true 